### ISSUE TITLE
@slash.requires decorator

### ISSUE THREAD

**Issue by QwistyS** [getslash/slash#1042]
Hi I have the following code
@slash.requires(radar.board.is_cv, message="The test not support on CV board")
def test_read_fpga_id():
assert 1==1

The error I have is:
'NoneType' object has no attribute 'is_cv'

but when I'm using the following approach:
def test_read_fpga_id():
    if radar.board.is_cv:
        slash.skip_test(The test not support on CV board")
    assert 1 == 1
all working well
I'm referesing the same object.

So my conclusion will be the decorator is loading at the Slash run time before the instance of radar class was created.
if that the way: any workaround that?
else: what I'm doing wrong?

**Comment by ayalash** [comment]
@QwistyS Tests requirements are being checked just before calling test_start and checking building its fixtures.  In this phase slash will call your requires callback.
In your case, I think that your problem is that the callback doesn't exist yet - This is done by python (not slash) in import level.

The approach you wrote as workaround will still perform all test setup and loading fixtures (if there are any).
I think a better approach will be:
```
def is_cv_radar_board():
    return radar.board.is_cv()

@slash.requires(is_cv_radar_board, message="The test not support on CV board")
def test_read_fpga_id():
    assert 1==1
```
