### ISSUE TITLE
Preferred Method of Writing Tests

### ISSUE THREAD

**Issue by will7007** [getslash/slash#1055]
Is the preferred method of writing Slash tests to use functions (the only method mentioned in the ["Writing Tests"](https://slash.readthedocs.io/en/master/tour.html#writing-tests) section of the docs) or is the use of class-based tests equally acceptable? I ask because there are several issues here that mention that class-based tests are not recommended, but references to class-based tests are still present in the [docs](https://slash.readthedocs.io/en/master/errors.html?highlight=slash.Test#explicitly-adding-errors-and-failures):
- #453
- #599
- #948
- #953

Based on the conversations and issues here, it seems like class-based tests are not recommended and were planned for removal at some point. Are they only present currently as a deprecated feature, or has their removal been re-evaluated in the time since these issues were posted? I would like to evaluate if our team should switch to using class-based tests because I like the before/run/after setup--which we admittedly could replicate without using class-based tests--but I want to make sure that class tests won't disappear in later versions of Slash.

**Comment by vmalloc** [comment]
Hi @will7007 ! First sorry for the late response. I was on vacation and I had little time to answer.

Our original plan was to deprecate class-based tests to simplify things inside the Slash framework itself, but unfortunately most of us now find ourselves with very little time to invest in the project apart from occasional PR reviews and small maintenance work. This means it is currently unlikely for a big, backwards-compatibility-breaking release to appear all of a sudden in the near future. 

However, as a general direction for the project I do think class-based tests are less preferable, and the same goals are more easily achieved with composition rather than inheritence.

Hope that answers the question
