### ISSUE TITLE
[fixtures] cleanups with different scopes works only for the first one

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#414]
As far as i investigate it related to push/pop cleanup mechanism.

code for reproduction:
```
import slash

@slash.fixture(scope='session')
def fix_a():
	def cleanup():
		print 'cleanup'
	
	slash.add_cleanup(cleanup, critical=True, scope='test')
		
	return 'fixture'

@slash.parametrize('a', range(3))
def test_a(fix_a, a):
    pass
```

**Comment by vmalloc** [comment]
Cleanups are a stack to which cleanup callbacks are added with `add_cleanup` and popped automatically when it's time for the cleanup to be called. Your example is not supported usage because you're adding a cleanup to a stack that hasn't formed yet (the `test` scope stack).

I opened a second issue for improving the error message in such cases (#415)

What exactly are you trying to accomplish?

**Comment by eplaut** [comment]
Hi,
My system using VMs as as part of the tests. to save time I want to be able to use the same VM for the whole session, and perform a cleanup between each test.

for now I see that I can use a test-scope fixture that uses the session-scope one and perform the cleanup from there, but I do think my usage is legit and I'm asking for support for it.

Many thanks!

**Comment by vmalloc** [comment]
We're planning to support `this.before_test` and `this.after_test` for fixtures, which will be useful for session and module-scoped fixtures (see #195) - I think this would provide a solution to what you're looking for.

**Comment by eplaut** [comment]
Thanks
