### ISSUE TITLE
Using generator in slash.parametrize

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#478]
Hi!

On current state `slash.parametrize` will expend all return values to list ( https://github.com/getslash/slash/blob/develop/slash/core/fixtures/parameters.py#L98 ).
I want to use it to control running tests, for example:
```
def my_xrange(max_number):
    for i in xxrange(max_number):
        if slash.g is True:
             break
        yield i

def my_func_is_less_than_5(num):
    return num < 5

@slash.parametrize('num', xrange(10))
def test_my_func(num):
     try:
         assert my_func_is_less_than_5(num)
     finally:
         slash.g = True
```
I expected that it will stop on first fail. reading all values at beginning can't be manged while tests are running.

**Comment by vmalloc** [comment]
This is by design. Slash has to know the full set of tests it intends to run before beginning the run due to the internal architecture of how fixtures and parametrizations are spanned.

Also, your're not supposed to *replace* `slash.g`, but assign under it (like `slash.g.condition = True`)

If you need a test that considers a dynamic variable for cases you need to encapsulate that logic within the test itself.
