### ISSUE TITLE
Errors and failures are logged as 'DEBUG'

### ISSUE THREAD

**Issue by ViktorFagerlind** [getslash/slash#707]
When using slash.add_error and slash.add_failure these are logged as 'DEBUG'. It would be more natural to log them as 'ERROR' (in my opinion).

Log excerpt:
[2017-12-21 08:19:30.921294] DEBUG: slash.core.result: Error added: BC1553 Error!

**Comment by vmalloc** [comment]
This is a very good question actually, and we debated it a lot in the beginning. In the approach we have taken thus far, catching errors from tests are a part of what Slash is supposed to do, and hence are not considered errors at the log level. They are DEBUG so that you can later look at the raw exception captured when going through the logs.

Having said that I realized that this is an issue of personal preference and hence perhaps will be a good match for a custom configuration parameter. This could be something like `log.added_errors_level=DEBUG`. What do you think?

**Comment by vmalloc** [comment]
So still following your suggestion - let's say I as a user choose the "SUT" approach. What would you suggest we do with Slash logs that have low levels (such as "TRACE" or DEBUG)? I would guess to eliminate them altogether, right?

**Comment by vmalloc** [comment]
When I come to think about it, what you're actually suggesting is "Slash develop mode", which, if False, means Slash practically emits no logs except for critical ones...

**Comment by vmalloc** [comment]
@ViktorFagerlind I think that the traceback should have a DEBUG level anyways. Otherwise the screen becomes very hard to read when there are lots of errors... What do you think?

**Comment by ViktorFagerlind** [comment]
Yes, that's what I meant, "Slash develop mode" seems like a good idea! Another potential solution would be to log the internal slash stuff into a separate log file.

I agree that the traceback should be DEBUG. Often you only look at higher layer logging and then you don't want it to be too verbose.

**Comment by vmalloc** [comment]
Ok. So after discussing with @ayalash we decided to have a configuration parameter controlling Slash's own verbosity level (regarding its own logs), which will be set, by default, to WARNING. That, in addition to an additional error log for added errors should give you what you want. How does that sound?

**Comment by ViktorFagerlind** [comment]
That sounds good!

**Comment by vmalloc** [comment]
Opened #719
